definitions:
  app.Pager:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total_rows:
        type: integer
    type: object
  errcode.Error:
    type: object
  model.Tag:
    properties:
      create_time:
        type: integer
      created_by:
        type: string
      delete_time:
        type: integer
      id:
        type: integer
      is_del:
        type: integer
      name:
        type: string
      state:
        type: integer
      update_time:
        type: integer
      updated_by:
        type: string
    type: object
  model.TagSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
    type: object
info:
  contact:
    name: ChinKai Ting
    url: http://www.swagger.io/support
  description: Go 再強一點
  termsOfService: http://swagger.io/terms
  title: gobook-ch2
  version: "1.0"
paths:
  /api/v1/tags:
    get:
      parameters:
      - description: tag name
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: status
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: page num
        in: query
        name: page
        type: integer
      - description: page display num
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: Getting list of tags
swagger: "2.0"
